name: check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Consistency check
        run: python3 scripts/check.py
